export default {
	bargraph: {
		width: 'calc(100% - 8)',
		height: 75,
		margin: 4,
	},
	bglegend: {
		flexWrap: 'wrap',
		display: 'flex',
		justifyContent: 'center',
		height: 'auto',
		width: 'calc(100% - 20px)',
		margin: 0,
		marginLeft: 10,
		marginRight: 10,
		marginBottom: 20,
	},
	legendPair: {
		display: 'inline-flex',
		alignItems: 'center',
		margin: 5,
	},
	legendColor: {
		display: 'inline-block',
		opacity: .7,
		height: 15,
		width: 15,
		borderRadius: '50%',
		marginRight: 5,
	},
	legendCategory:{
		fontSize: 12,
		color: '#000',
	},
	legendEntry: { /* The container for the text and squares. */
		display: 'inline-flex',
		alignItems: 'center',
		justifyContent: 'center',
		width: 'auto',
		height: 20,
		padding: 2,
		marginLeft: '1vw',
		borderStyle: 'solid',
		borderWidth: 1,
		borderColor: 'rgba(0, 0, 0, .25)',
		borderRadius: 0,
	},
	dataSelector: {
		marginLeft: '7%',
	},
	summaryContent: {
		width: '100%',
		height: 'auto',
		overflow: 'scroll',
	},
	reportBox: {
		padding: 5,
		position: 'relative',
        borderRadius: 0,
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
	},
	countText: {
		fontSize: 14,
	},
	caseBDText: {
		marginLeft: 10,
		color: 'rgba(0,0,0,.7)',
	},
	recString: {
		borderWidth: 0,
		borderBottomWidth: 1,
		width: 'calc(100% - 8px)',
		fontSize: 12,
	},
	keywordHead: {
		position: 'relative',
		display: 'flex',
		flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        margin: 0,
        height: 30,
        backgroundColor: '#dbf0ff',
        borderWidth: 0,
        borderBottomWidth: 1,
        borderTopWidth: 1,
        borderStyle: 'solid',
        borderColor: 'rgba(0,0,0,.25)',
	},
	textButton: {
		color: '#1D1F83',
		margin: 5,
        '&:hover': {
        	cursor: 'pointer',
        }
	},
	recButton: {
		display: 'flex',
		alignItems: 'center',
		fontSize: 12,
		color: '#1D1F83',
		margin: 0,
		height: 30,
		marginLeft: '15%',
		'&:hover': {
        	cursor: 'pointer',
        	color: '#fff',
        }
	},
	caseButton: {
		marginLeft: '5%',
		color: '#1D1F83',
        '&:hover':{
        	cursor: 'pointer',
        	textDecoration: 'underline',
        },
	},
	keywordContainer: {
		display: 'flex',
		height: 'auto',
		width: 'auto',
		padding: 10,
		alignItems: 'center',
	},
	keywordCapsule: {
		display: 'inline-block',
		height: 'auto',
		width: 'auto',
		margin: 2,
		opacity: .7,
		borderRadius: 15,
		'&:hover':{
			cursor: 'pointer',
		},
	},
	topButton: {
		width: '50%',
		display: 'inline-block',
	},
}